### ISSUE TITLE
Improper format

### ISSUE THREAD

**Issue by comann** [bq/poeditor-android-gradle-plugin#1]
Great project. I am using to convert my strings from PoEditor. However, I am running into problems with the format of the generated values folders. For example,

values-zh-CN - android studio does not like the format and expects it the CH to be prefaced with an r. Further, any secondary region specifier should be prefaced with an r in my understanding.

Please help.

**Comment by imartinez** [comment]
Hi @comann,

thank you for using this project, I'm glad it is useful for you.

I've just implemented the region specific language support. I've opened a pull request in order to have this feature merged to the main repo (https://github.com/bq/poeditor-android-gradle-plugin/pull/3). 

In the meantime **you can already test the fix on your projec**t by pointing to an updated version of the project coming from my fork:

**Use**
classpath 'com.github.imartinez:poeditor-android-gradle-plugin:0.2.6'
**instead of** 
classpath 'com.github.bq:poeditor-android-gradle-plugin:0.2.5'

let me know if it works correctly,
regards!

**Comment by comann** [comment]
Is there any timeline on when this will be  merged in and released to jitpack.io?

**Comment by imartinez** [comment]
I'm not sure there is.

In the meantime, the new version is already available on jitpack.io by using:
classpath 'com.github.imartinez:poeditor-android-gradle-plugin:0.2.6'

I hope this helps.
