### ISSUE TITLE
Doubled "%"

### ISSUE THREAD

**Issue by prof0021** [bq/poeditor-android-gradle-plugin#13]
**SW details (please complete the following information):**
 - IDE version: Android Studio 4.0.1
 - Plug-in Version: 1.0.0
 - System: Windows 10

**Summary and background of the bug**
All the occurrences of "%" are doubled. 

Eg. 
- Authentication error: %s! -> Authentication error: %%s!
- %1$s - %2$s -> %%1$s - %%2$s

Another problem: all the string have been put into quotation marks

Eg.
- Profile -> "Profile"

**Steps to reproduce**
Just execute: gradlew importPoEditorStrings

**Expected behavior**
I expect that these parameters ("%") string stay unattached

**Current behavior**
All the occurrences of "%" are doubled. 

![2020-08-07 12_54_57-strings xml (C__Projects_Android_mv7-android_app_src_main_res_values)  Default C](https://user-images.githubusercontent.com/16061015/89639074-39453480-d8ad-11ea-9047-a857929b28fa.png)

**Comment by adriangl** [comment]
Hi @prof0021! First of all, thanks for using the plugin!

About the issue with the `"`, that's how PoEditor exports the strings, so we can't do much about it. The raw exported exported files from PoEditor already append the quotation marks in all strings. Anyway, this shouldn't pose any problem when developing since that format is accepted by Android strings.

Regarding the double `%`, for now that's how the plug-in behaves, as it assumes that you're using the custom syntax we developed for text variables. 
This syntax is explained in https://github.com/bq/poeditor-android-gradle-plugin#handle-placeholders. It allows us to be more explicit about the variables we define and helps translators by giving them more context about the variables. If you have any questions about the syntax, don't hesitate to ask :)

I hope this clears up the questions!

**Comment by adriangl** [comment]
I close the issue due to inactivity.
Feel free to open it again if needed 😉
